cmake_minimum_required(VERSION 3.25)
project(nx-glow VERSION 0.1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_AUTOMOC ON)
set(BUILD_SHARED_LIBS ON)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")
find_package(Qt6 REQUIRED COMPONENTS Widgets)
find_package(KWin 6.7 REQUIRED)
find_package(KF6CoreAddons REQUIRED)
kcoreaddons_add_plugin(nxglow SOURCES src/glow.cpp INSTALL_NAMESPACE "kwin/effects/plugins")
set_target_properties(nxglow PROPERTIES PREFIX "")
target_link_libraries(nxglow PRIVATE KWin::kwin)
target_compile_options(nxglow PRIVATE -Wall -Wextra)
